### PR TITLE
Fixed linting errors

### PR DESCRIPTION
**Pull request by NULLx76**
The style was inconsistent and incorrect. Made use of eslint with the airbnb style guide to fix this.

### CODE REVIEW

**Comment by NULLx76** [comment]
The tests are now failing but this is expected behaviour as they should have been failing all along because previously the code just returned an error, which doesn't do anything because nothing ever does anything with the return value. Now it actually shows it and therefore fails the test (If I understand the code correctly that is).

**Comment by chauff** [comment]
While I appreciate the effort, this pull request contains ES6 features we are not using in class.

**Comment by RobbinBaauw** [comment]
These ES6 features are widely used nowadays, and in the code `let` was already used here:
https://github.com/chauff/Web-Teaching/blob/abdb53f06ce9f717ca4a9d5dc6226c51956ea2b9/demo-code/balloons-game/app.js#L53-L55

Arrow functions are also already used:
https://github.com/chauff/Web-Teaching/blob/abdb53f06ce9f717ca4a9d5dc6226c51956ea2b9/demo-code/balloons-game/app.js#L20-L22

Both of these are from the ES6 spec. 

So as far as I can see we only added template literals and argument destructuring which weren't used in the original. But these are very easy concepts, so if there was a single mention on what those things actually do in some sort of README, this should be plenty, or am I mistaken?

We also removed all mentions to `arguments.callee`, as it's [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee) so people shouldn't use it.

**Comment by jonay2000** [comment]
you can easily replace the (req,res) => {body} with function(req,res){body} to make it less ES6. still i agree that this is a lot better.

**Pull request closed without merging**
